### ISSUE TITLE
Expose remotes:::parse_git_repo

### ISSUE THREAD

**Issue by richfitz** [MangoTheCat/remotes#13]
Any chance this could be exposed?  I have a couple of use cases for it (building drat repositories mostly, but it's come up a few times).  Understand if you want to keep the package super simple though.

**Comment by gaborcsardi** [comment]
Hmmm. In general I don't really want to export the little pieces like this. It is quite small, so I think you can just take the code, if you are fine with the license.

**Comment by jennybc** [comment]
I have exactly the same request. How do I resolve the fact that the same code appears here (MIT) and in devtools (GPL) and originated in devtools?

**Comment by gaborcsardi** [comment]
@jennybc My mistake, then `remotes` must be GPL, too.

**Comment by gaborcsardi** [comment]
@jennybc Just changed the license, sorry for the confusion. I guess I just assumed that like most of Hadley's stuff, `devtools` was MIT.

On the other hand, `remotes` is not using any code from R-core AFAIK, and since the code was mostly written by Hadley and me, I guess he could licence that code with MIT and then `remotes` could be MIT.

@hadley ?

**Comment by jennybc** [comment]
Now sort of sorry I asked but I suppose it had to get straightened out.

Back to the original topic, `remotes:::parse_git_repo` is little but very useful in many contexts. I wholeheartedly :+1: @richfitz's request to export it.

**Comment by gaborcsardi** [comment]
@jennybc @richfitz can you please tell me very briefly how you would use this? 

I am thinking that maybe another package would be a better place for it, some github-related package.

**Comment by richfitz** [comment]
I currently use a parser in [drat.builder](https://github.com/richfitz/drat.builder) for fetching a collection of gh packages into a drat (e.g. [here](https://github.com/richfitz/drat)).

I did a similar thing in [dockertest](https://github.com/traitecoevo/dockertest) though I'll probably re-implement that on top of drat.builder because it deals better with the dependency sort on installation. It doesn't use devtools-style strings yet but it should.

I am also using a parser in [context](https://github.com/dide-tools/context) for specifying sources of non-CRAN packages for later installation on a remote computer.  It works internally by building a file-based drat repo.

An aside, if you did make it public you'd be able to extend the syntax beyond github so that:

* `github:MangoTheCat/remotes` and `MangoTheCat/remotes` were equivalent
* `bitbucket:username/repo` would work with bitbucket.

Or `github://` or whatever.

**Comment by gaborcsardi** [comment]
Then maybe we can create another package for this? With some similar functions, if there are any more.... `ghrefs`?

If we want it to be MIT, then we would need to rewrite the code, though. Or ask @hadley and @krlmlr for an MIT license. They wrote all of the current version it seems:
https://github.com/hadley/devtools/blame/2fc4f84ba23ddc97b535c6ac4dfcfa122d8269a7/R/install-github.r#L209-L328

**Comment by richfitz** [comment]
Sure, though I think the approach is more general than github only (though practically they're becoming more and more the only game in town which is a little sad tbh).  grefs?  I know you love micropackages at the moment...

**Comment by gaborcsardi** [comment]
`g` for `git`? Then how about `gitrefs`?

**Comment by jennybc** [comment]
Maybe this hypothetical package is what should be called `remotes` instead of this one 😀. `vcremotes`? It isn't great but works for Git/GitHub and yet isn't hyper-specific to it.

Other functions: in the same email that lead me to look here, I'd asked that [`devtools::github_remote_parse()`](https://github.com/hadley/devtools/blob/81dd313e1d143a3bdaaa2e1f09c887801db66694/R/git.R#L100-L117) also be exposed, though it is yet smaller and even easier to re-do for yourself. Another micro function fit for a micropackage: the function that grabs PAT from an environment variable. Might encourage people to coordinate expectations for env var names (c.f. `GITHUB_PAT` vs. `GITHUB_TOKEN`).

I want `parse_git_repo()` for that novice-friendly git (git2r) and github (gh) wrapper that I described to you in December @gaborcsardi. User might provide info about something they want to fork or to add as a remote as a URL they got from their browser.

**Comment by gaborcsardi** [comment]
> Maybe this hypothetical package is what should be called remotes instead of this one 😀

Yeah. OK, I'll export the one here. :)

**Comment by gaborcsardi** [comment]
I renamed it to `parse_github_repo_spec`, that is a better name I think.

**Comment by richfitz** [comment]
Great, thanks!
